### ISSUE TITLE
Update 2015 Wedding Showcase page to 2016 Page

### ISSUE THREAD

**Issue by MelissaHall** [hhgr/HeritageHillsResort#2]
Please update this page: http://www.heritagehillsresort.com/celebrate/2015-winter-private-showcase to have the URL for the 2016 wedding showcase.  We also need to make the form live, and add the option to select which date they will be attending, either January 13 or January 14.

Due date October 15th please.

**Comment by AdamChlan** [comment]
@MelissaHall What do you think about removing the date from the URL altogether?

**Comment by MelissaHall** [comment]
That's a great solution. thanks!

**Comment by AdamChlan** [comment]
@MelissaHall I added the date picker to the form. I'm going to close this out. Let me know if you need anything else.
