### ISSUE TITLE
Replace Cigar Night Announcement with Egg Nog Jog

### ISSUE THREAD

**Issue by derekober** [hhgr/HeritageHillsResort#3]
Adam, 
Since the Cigar Night will occur tomorrow, I'm just making a note to ask that we replace this call-out announcement on the hhgr.com homepage with one for the Egg Nog Jog by Thursday, 10/15. If you need information I can definitely send over the final flyer, etc. Thanks!

**Comment by MelissaHall** [comment]
Derek - I can show you how to do this - It's easy.

We may need to hold off on Egg Nog Jog, as we don't have the details final yet (I know Sally plans to discuss that more at tomorrow's event meeting)

**Comment by derekober** [comment]
Ah okay I’m sorry I missed that we were still working on that event! ☹
