### ISSUE TITLE
HHGR.com

### ISSUE THREAD

**Issue by derekober** [hhgr/HeritageHillsResort#5]
Adam, 

The links for each First & Platinum Class "Enroll Now" buttons on this page do not link to the sign up page:

http://www.heritagehillsresort.com/?/passport-to-perks/membership-benefits/

Hopefully a very easy fix!

**Comment by AdamChlan** [comment]
Derek, this has been fixed.

**Comment by derekober** [comment]
Thank you!

Derek A. Ober
Sales and Marketing Administrator
Heritage Hills
717.755.0123 ext. 1684
717.424.1566
