### ISSUE TITLE
Add Wedding Menu 

### ISSUE THREAD

**Issue by MelissaHall** [hhgr/HeritageHillsResort#7]
Adam - I'm trying to upload a new wedding menu but I keep getting the error file path not valid. Can you upload for me? Attached here.

[wedding-menu.pdf](https://github.com/hhgr/HeritageHillsResort/files/118237/wedding-menu.pdf)

**Comment by AdamChlan** [comment]
Melissa, I have fixed the path and uploaded the the menu to the PDF area. Is there somewhere else you needed it to be?

**Comment by AdamChlan** [comment]
Going to close this out. Let me know if you need anything else
